/*
 * SMS API
 *
 * With the Nexmo SMS API you can send SMS from your account and lookup messages both messages that you've sent as well as messages sent to your virtual numbers. Numbers are specified in E.164 format. More SMS API documentation is at <https://developer.nexmo.com/messaging/sms/overview>
 *
 * API version: 1.0.5
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sms

import (
	"bytes"
	"encoding/json"
)

// Error struct for Error
type Error struct {
	// The amount of messages in the request
	MessageCount *string `json:"message-count,omitempty"`
	Messages *[]ErrorMessage `json:"messages,omitempty"`
}

// GetMessageCount returns the MessageCount field value if set, zero value otherwise.
func (o *Error) GetMessageCount() string {
	if o == nil || o.MessageCount == nil {
		var ret string
		return ret
	}
	return *o.MessageCount
}

// GetMessageCountOk returns a tuple with the MessageCount field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Error) GetMessageCountOk() (string, bool) {
	if o == nil || o.MessageCount == nil {
		var ret string
		return ret, false
	}
	return *o.MessageCount, true
}

// HasMessageCount returns a boolean if a field has been set.
func (o *Error) HasMessageCount() bool {
	if o != nil && o.MessageCount != nil {
		return true
	}

	return false
}

// SetMessageCount gets a reference to the given string and assigns it to the MessageCount field.
func (o *Error) SetMessageCount(v string) {
	o.MessageCount = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *Error) GetMessages() []ErrorMessage {
	if o == nil || o.Messages == nil {
		var ret []ErrorMessage
		return ret
	}
	return *o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Error) GetMessagesOk() ([]ErrorMessage, bool) {
	if o == nil || o.Messages == nil {
		var ret []ErrorMessage
		return ret, false
	}
	return *o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *Error) HasMessages() bool {
	if o != nil && o.Messages != nil {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []ErrorMessage and assigns it to the Messages field.
func (o *Error) SetMessages(v []ErrorMessage) {
	o.Messages = &v
}

type NullableError struct {
	Value Error
	ExplicitNull bool
}

func (v NullableError) MarshalJSON() ([]byte, error) {
    switch {
    case v.ExplicitNull:
        return []byte("null"), nil
    default:
		return json.Marshal(v.Value)
	}	
}

func (v *NullableError) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}

