/*
 * SMS API
 *
 * With the Nexmo SMS API you can send SMS from your account and lookup messages both messages that you've sent as well as messages sent to your virtual numbers. Numbers are specified in E.164 format. More SMS API documentation is at <https://developer.nexmo.com/messaging/sms/overview>
 *
 * API version: 1.0.5
 * Contact: devrel@nexmo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sms

import (
	"bytes"
	"encoding/json"
)

// Sms struct for Sms
type Sms struct {
	// The amount of messages in the request
	MessageCount *string `json:"message-count,omitempty"`
	Messages *[]Message `json:"messages,omitempty"`
}

// GetMessageCount returns the MessageCount field value if set, zero value otherwise.
func (o *Sms) GetMessageCount() string {
	if o == nil || o.MessageCount == nil {
		var ret string
		return ret
	}
	return *o.MessageCount
}

// GetMessageCountOk returns a tuple with the MessageCount field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Sms) GetMessageCountOk() (string, bool) {
	if o == nil || o.MessageCount == nil {
		var ret string
		return ret, false
	}
	return *o.MessageCount, true
}

// HasMessageCount returns a boolean if a field has been set.
func (o *Sms) HasMessageCount() bool {
	if o != nil && o.MessageCount != nil {
		return true
	}

	return false
}

// SetMessageCount gets a reference to the given string and assigns it to the MessageCount field.
func (o *Sms) SetMessageCount(v string) {
	o.MessageCount = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *Sms) GetMessages() []Message {
	if o == nil || o.Messages == nil {
		var ret []Message
		return ret
	}
	return *o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Sms) GetMessagesOk() ([]Message, bool) {
	if o == nil || o.Messages == nil {
		var ret []Message
		return ret, false
	}
	return *o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *Sms) HasMessages() bool {
	if o != nil && o.Messages != nil {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []Message and assigns it to the Messages field.
func (o *Sms) SetMessages(v []Message) {
	o.Messages = &v
}

type NullableSms struct {
	Value Sms
	ExplicitNull bool
}

func (v NullableSms) MarshalJSON() ([]byte, error) {
    switch {
    case v.ExplicitNull:
        return []byte("null"), nil
    default:
		return json.Marshal(v.Value)
	}	
}

func (v *NullableSms) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}

